In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import jaccard_score, f1_score

The masks will need to be thresholded, as there may have been some interpolation when they were produced (show example here). Not all massk have 3 examples as well.

In [2]:
NUM_IMAGES = 45

images = [cv2.imread(f'./puzzle_data/images/image-{i}.jpg') for i in range(NUM_IMAGES)]



In [3]:
masks_0 = [cv2.threshold(cv2.imread(f'./puzzle_data/masks/mask-{i}-0.png', cv2.IMREAD_GRAYSCALE), 127, 255, cv2.THRESH_BINARY)[1] for i in range(NUM_IMAGES)]
masks_1 = [cv2.threshold(cv2.imread(f'./puzzle_data/masks/mask-{i}-1.png', cv2.IMREAD_GRAYSCALE), 127, 255, cv2.THRESH_BINARY)[1] for i in range(NUM_IMAGES)]
masks_2 = [cv2.threshold(cv2.imread(f'./puzzle_data/masks/mask-{i}-2.png', cv2.IMREAD_GRAYSCALE), 127, 255, cv2.THRESH_BINARY)[1] for i in range(NUM_IMAGES)]

In [5]:
masks_2[2].shape


(3840, 5120)

Not all images are exactly the same size (see image 7)

In [5]:
dim = (3840, 5120)
for i in range(len(images)):
	try:
		if masks_0[i].shape != dim: print(f'Image {i} Mask {0} different size: {masks_0[i].shape}')
		masks_0[i] = cv2.resize(masks_0[i],dim)
	except:
		pass
	try:
		if masks_1[i].shape != dim: print(f'Image {i} Mask {1} different size: {masks_1[i].shape}')
		masks_1[i] = cv2.resize(masks_1[i],dim)
  
	except:
		pass
	try:
		if masks_2[i].shape != dim: print(f'Image {i} Mask {2} different size: {masks_2[i].shape}')
		masks_2[i] = cv2.resize(masks_2[i],dim)
  
	except:
		pass

Image 7 Mask 0 different size: (3844, 5120)
Image 33 Mask 2 different size: (3848, 5120)
Image 43 Mask 2 different size: (3844, 5120)


The masks are not all identical, see below. Some form of interpolation will need to be performed to reconcile the diferences

The images are very large `(3840, 5120, 3)`, and so to speed up processing they will likely have to be scaled down. This may lead to some artifacts in the trianing data that may affect the model performance.

In [6]:
ValueError

ValueError

In [7]:
for i in range(len(images)): 
	agr1 = jaccard_score(masks_0[i], masks_1[i], average='micro')
	
	try:
		agr2 = jaccard_score(masks_0[i], masks_2[i], average='micro')
		agr3 = jaccard_score(masks_1[i], masks_2[i], average='micro')
	
		print(f'Image {i} average jaccard score: {(agr1 + agr2 + agr3)/3}')
	except:
		print(f'Image {i} average jaccard score: {agr1}')
		



ValueError: multiclass-multioutput is not supported

In [ ]:
for i in range(len(images)): 
    try: 
        agr1 = f1_score(masks_0[i], masks_1[i], average='micro')
        agr2 = f1_score(masks_0[i], masks_2[i], average='micro')
        agr3 = f1_score(masks_1[i], masks_2[i], average='micro')
        
        print(f'Image {i} average f1 score: {(agr1 + agr2 + agr3)/3}')
    except: 
        pass


Image 0 average f1 score: 0.9960759572088698
Image 1 average f1 score: 0.9790806093892567
Image 2 average f1 score: 0.9857249226669142
Image 4 average f1 score: 0.9953785781014673
Image 5 average f1 score: 0.9941481553052585
Image 6 average f1 score: 0.9809097442476135
Image 8 average f1 score: 0.992939650292465
Image 9 average f1 score: 0.9958599477824898
Image 11 average f1 score: 0.9926426359033282
Image 12 average f1 score: 0.9863616826092447
Image 13 average f1 score: 0.9961424536443948
Image 14 average f1 score: 0.9742287901515962
Image 15 average f1 score: 0.9900088580617444
Image 18 average f1 score: 0.9200283814166853
Image 19 average f1 score: 0.9928785078940315
Image 20 average f1 score: 0.9617981885727617
Image 21 average f1 score: 0.9887464822903942
Image 22 average f1 score: 0.9685814566630239
Image 24 average f1 score: 0.984274235933244
Image 25 average f1 score: 0.9912715147889245
Image 26 average f1 score: 0.9934029059325741
Image 28 average f1 score: 0.334527740948511